version: '2'

services:
  app:
    image: 'demo-test:1.0.0'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo-test
  db:
    image: 'postgres:12.12'
    container_name: db
    environment:
      - POSTGRES_DB=demo-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root