apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-test-config-map
data:
  application.yml: |
    spring:
  application:
    name: demo-test
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo-test
    username: postgres
    password: root

    notification:
      periodOfDbCheck:
        milliseconds: 10000
      beforeDeparture:
        seconds: 86400
