-- changeset ilya_maslov :1.0.1
CREATE TABLE department
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_name   VARCHAR(255) NOT NULL,
    CONSTRAINT "departmentPK" PRIMARY KEY (id)
);
