-- changeset ilya_maslov :1.0.2
CREATE TABLE department
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    departmentName   VARCHAR(255) NOT NULL,
    CONSTRAINT "departmentPK" PRIMARY KEY (id)
);

INSERT INTO department (departmentName)
VALUES ('RISKI'),
       ('BIGDATA'),
       ('TECH');

CREATE SEQUENCE seq_department START 10 INCREMENT 1;