-- changeset ilya_maslov :1.0.2
CREATE TABLE post
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_name         VARCHAR(255) NOT NULL,
    CONSTRAINT "postPK" PRIMARY KEY (id)
);
