-- changeset ilya_maslov :1.0.3
CREATE TABLE employee
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_name                VARCHAR(128)    NOT NULL,
    first_name               VARCHAR(128)    NOT NULL,
    middle_name              VARCHAR(128)    NOT NULL,
    birth_date               date            NOT NULL,
    department_id            BIGINT          NOT NULL,
    post_id                  BIGINT          NOT NULL,
    CONSTRAINT "employeePK" PRIMARY KEY (id)
);
