-- changeset ilya_maslov :1.0.3
CREATE TABLE post
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    postName         VARCHAR(255) NOT NULL,
    CONSTRAINT "postPK" PRIMARY KEY (id)
);

INSERT INTO post (postName)
VALUES ('JUNIOR'),
       ('MIDDLE'),
       ('SENIOR');

CREATE SEQUENCE seq_post START 10 INCREMENT 1;